[package]
name = "plotka_core"
version = "0.1.0"
authors = ["micouy <szpontaniczny@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "^1.0"
serde = "^1.0"
csv = "^1.0"
pretty_assertions = "^0.5"
actix = "^0.7"
actix-web = "^0.7"
log = "^0.4"
rand = "^0.6"
